### ISSUE TITLE
MNE incompatible with TD-fNIRS

### ISSUE THREAD

**Issue by P-Oveisi** [GriffithsLab/kernel-flow-tools#45]
When trying to use the `mne.io.read_raw_snirf()` the following error is raised:
`RuntimeError: MNE only supports reading continuous wave amplitude and processed haemoglobin SNIRF files. Expected type code 1 or 99999 but received type code 301`

I remember there was a workaround @JohnGriffiths ?

**Comment by JohnGriffiths** [comment]
What MNE version are you using?

The latest version should have the TD-fNIRS i/o support.

**Comment by P-Oveisi** [comment]
The MNE package is up to date (ver 1.0.3) but the problem seems to be the type of snirf that is to be imported. It has no problem loading HB moments, but cannot load moments files.
```
RuntimeError: MNE only supports reading continuous wave amplitude and processed haemoglobin SNIRF files. Expected type code 1 or 99999 but received type code 301
```
